### PR TITLE
added weatherApi controller and currencyConverter

### PR DESCRIPTION
**Pull request by CyemezoBrown**
# Description
This pull request has been added to help user to know the weather of certain place before or going to that place and also by the time there are at that place.
also help a user to know the currency in his own currency due to the accommodation cost per night so he/she  does need to move out of the this app to know the price in his/her currency.

## Type of change

Please check the options that are relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# How should this be manually tested or reproduced?
Open the endpoint `/api/v1/weather/weather?city="cityName"` for a GET request on the local development server.
 `x-rapidapi-key` : `39d2b5eb60msh9c338f352dc40efp17f5a9jsn93ca64d0491e`;
`x-rapidapi-host` :` community-open-weather-map.p.rapidapi.com`;
 to access the data of publicApi you need to add this data in the header.

Open the endpoint `/api/v1/convert/converter/9000?from=" "&to=" "` for a GET request on local development server.
to access the data of converter of currency.

# Checklist:

-  [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

# Screenshots (if applicable)

### CODE REVIEW

**Review by salviosage — COMMENTED** [review]
your PR has some conflicts , please resolve them

**Comment by Anguandia** [comment]
How should I manually test this PR @CyemezoBrown?

**Review by songa1 — APPROVED** [review]

**Review by Cyusa144 — COMMENTED** [review]
remove the commented lines

**Review by Cyusa144 — APPROVED** [review]

**Review by Alice-Gatera — APPROVED** [review]

**Review by salviosage — APPROVED** [review]
LGTM

**Pull request merged**
